### ISSUE TITLE
The value of the constructed RValue has a BoogieType ([int]int) that is incompatible with its CType ($Pointer$)

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#359]
IllegalArgumentException: The value of the constructed RValue has a BoogieType ([int]int) that is incompatible with its CType ($Pointer$)

termination/termcomp2016/C/SV-COMP_Mixed_Categories/rekcba_nxt_false-unreach-call.1.M1.c
settings/buchiAutomizer/termcomp2017-Noproofs.epf
toolchains/AutomizerAndBuchiAutomizerCInlineWithBlockEncoding.xml

**Comment by invd** [comment]
I still see this issue with today's Ultimate 8de8874bb85c5cb95aa1930e149dec9dbc679170 against Trezor bootloader code, so the underlying issue is not completely fixed. 

```
[2018-07-06 12:11:48,111 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
java.lang.IllegalArgumentException: The value of the constructed RValue has a BoogieType ([int]int) that is incompatible with its CType ($Pointer$).
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.checkType(RValue.java:94)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.<init>(RValue.java:78)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.<init>(RValue.java:66)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.ExpressionResult.switchToRValueIfNecessary(ExpressionResult.java:224)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.FunctionHandler.handleReturnStatement(FunctionHandler.java:511)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:1929)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:248)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:1192)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:287)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.FunctionHandler.handleFunctionDefinition(FunctionHandler.java:337)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:1574)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:210)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.processTUchild(CHandler.java:3968)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:2434)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:602)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:186)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.MainDispatcher.preRun(MainDispatcher.java:400)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.interfaces.Dispatcher.run(Dispatcher.java:260)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator.CACSL2BoogieTranslatorObserver.doTranslation(CACSL2BoogieTranslatorObserver.java:178)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator.CACSL2BoogieTranslatorObserver.finish(CACSL2BoogieTranslatorObserver.java:150)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:168)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:151)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:128)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:232)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:226)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:142)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:104)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:316)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.DefaultToolchainJob.run(DefaultToolchainJob.java:145)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by danieldietsch** [comment]
@invd could you attach the exact input file you used for this issue? And did you use one of the settings from ``settings/default/automizer/...`` without additional command line settings? 

Background: the error seen here (``the value of the constructed RValue has a BoogieType that is incompatible with its CType``) is a fallback that happens because something before missed an edge case.

**Comment by invd** [comment]
@danieldietsch: as described in direct communication, the issue is still present in version 472692297f66b14197f63de46ccd9873a7dc260c. A crashing example program has been provided via mail.

Notably, this problem can also triggered in variants of the program which have an empty main() function.

**Comment by danieldietsch** [comment]
Ok, good to know. For reference, the file is ``code/experiments/bootloader_code2/combined_09jan2018_nostrwidth_output_ultimate_emptymain.c```in invd's repository. 

I will minimize it and reference the minimized version here.

**Comment by invd** [comment]
Today's Ultimate 97aecd66c1162e91d286d38715432d609764915b still shows this issue on the Trezor code. After discussion with @danieldietsch and @jhoenicke, it appears that there are many ways to trigger this issue, which is rooted in Ultimate's inability to deal with certain implicit type conversions (see the minimal example that explores one variant of this).

**Comment by alexandernutz** [comment]
just a hint: usually the solution for this kind of issues is to add a "decayArrayToPointer" conversion (there is a method named like this in CHandler or so) at the right place in the translation (i.e., as soon as we can be sure that the array expression is used as a pointer).

**Comment by gschievelbein** [comment]
solved in commit febf0b9a418ed59cd75d0b33bca6e4fcd3db713e

**Comment by invd** [comment]
This issue is not fully fixed in Ultimate bd71e1ad3aca1ffdbbcf77b634ea1f3b625bca1a:

```
This is Ultimate 0.1.23-bd71e1a
[...]
[2018-08-01 21:05:09,653 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
java.lang.IllegalArgumentException: The value of the constructed RValue has a BoogieType ([int]int) that is incompatible with its CType ($Pointer$).
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.checkType(RValue.java:94)

```

I suspect that only one of several error conditions that lead to this exception has been addressed.

**Comment by danieldietsch** [comment]
The respective [regression test](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/regression/ctrans-bug-UOE-unsupportedrelation.c) is also still failing. 
@gschievelbein can you have another look?

**Comment by invd** [comment]
Trezor code is still affected, no improvement visible here. This is a major blocker.
3cea2480e0162cca93f99c9f013b388aca0ca196

Identical error message:
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: IllegalArgumentException: The value of the constructed RValue has a BoogieType ([int]int) that is incompatible with its CType ($Pointer$).
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: IllegalArgumentException: The value of the constructed RValue has a BoogieType ([int]int) that is incompatible with its CType ($Pointer$).: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.checkType(RValue.java:94)
```

**Comment by Heizmann** [comment]
Maybe I just fixed that.
https://github.com/ultimate-pa/ultimate/commit/39759c9d724777c19f1a01b3448a4e6bbda98403

**Comment by invd** [comment]
The issue still persists with the newest Ultimate 39759c9d724777c19f1a01b3448a4e6bbda98403 .

**Comment by Heizmann** [comment]
How can I reproduce this?

**Comment by danieldietsch** [comment]
@Heizmann See the minimal example.

**Comment by invd** [comment]
55903dff755ffb961c3d1e03797f004bb5b4d658 does **not** solve the issue for the Trezor code in question:

```
[2018-09-05 20:22:21,481 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
java.lang.IllegalArgumentException: The value of the constructed RValue has a BoogieType ([int]int) that is incompatible with its CType ($Pointer$).
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.checkType(RValue.java:94)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.<init>(RValue.java:78)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.<init>(RValue.java:66)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.ExpressionResult.switchToRValueIfNecessary(ExpressionResult.java:220)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.FunctionHandler.handleReturnStatement(FunctionHandler.java:511)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:1929)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java:249)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:1192)
```

**Comment by Heizmann** [comment]
Thanks for testing this so quickly.
Which is the program where this error occurs?

**Comment by danieldietsch** [comment]
I added a minimal example. 
@Heizmann The file in question is in invd's repository. There are two reasons why it is not in Ultimate's repo: 
* it should not be publicly accessible because it might hint at security issues in other peoples code
* it contains many C errors and warnings if run through our usual gcc check and would thus be ignored my other maintainers until those errors are fixed, which will not happen

**Comment by danieldietsch** [comment]
I think @gschievelbein may also look at this issue.

**Comment by Heizmann** [comment]
How urgent is this?
I can
* fix this particular problem quickly (next similar problem may pop up)
* fix the problem partially (some risk that it does not work)
* fix the problem (time-consuming, some risk that I will not finish this task within the next weeks)

**Comment by invd** [comment]
@Heizmann: the thesis is finished, therefore this is not acutely blocking time-critical academic research (anymore).

From an end user's perspective, the positive aspect here is that the error is triggered quickly and clearly during the translation phase (as opposed to crashing hours into a long run / producing a problematic result). However, since this error is triggered even with an empty main() function and no responsible code position is provided, there is little the user can do about it in a practical sense, even if time for some workarounds is available.

As I understand the issue, this specific error instance is caused by a programming error that shares the resulting symptoms with potentially many other "unrelated" programming errors in other places that have similar effects. This of course complicates the work here in the issue tracker when dealing with those, as seen before. Fixing the underlying problem *in a general sense* likely requires major changes to the type handling of Ultimate, and I can't weigh in on that decision. It would, however, be nice to have improved test coverage over the involved type situations / conversions to reduce the likelihood of unnoticed regressions (which is what we're dealing with here).

**Comment by invd** [comment]
With the newest Ultimate 0.1.23-25d9b6c, this error appears to be back again:
```
[2018-09-25 00:02:00,983 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
java.lang.IllegalArgumentException: The value of the constructed RValue has a BoogieType ([int]int) that is incompatible with its CType ($Pointer$).
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.checkType(RValue.java:94)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.<init>(RValue.java:78)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.<init>(RValue.java:66)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.ExpressionResult.switchToRValueIfNecessary(ExpressionResult.java:220)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.FunctionHandler.handleReturnStatement(FunctionHandler.java:515)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:1890)
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.PRDispatcher.dispatch(PRDispatcher.java
```
The relevant Trezor source file from two weeks ago can be used to reproduce this. The relevant output is for the _svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf_ setting.

With _svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf_, the error is very similar:
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: IllegalArgumentException: The value of the constructed RValue has a BoogieType ([bv32]bv8) that is incompatible with its CType ($Pointer$).
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: IllegalArgumentException: The value of the constructed RValue has a BoogieType ([bv32]bv8) that is incompatible with its CType ($Pointer$).: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.RValue.checkType(RValue.java:94)
```

@danieldietsch: should I reopen this issue?

**Comment by gschievelbein** [comment]
I will work on this

**Comment by Heizmann** [comment]
I think I fixed it again in https://github.com/ultimate-pa/ultimate/commit/92f38635a7ab33d807a11f48a2585309c5561273 but please check if the problem is really gone.

**Comment by invd** [comment]
@Heizmann: 999701d2d06e8e4e7dfe99f51290a74b5e2609e4 appears to be fixed again, I'm able to reach the #377 output message. Thanks!
